import type { Command, StringMap } from "./types"
import { detectRepoRoot } from "./tracker/root"
import {
  issueChildren,
  issueClose,
  issueCreate,
  issueList,
  issueMetaGet,
  issueMetaSet,
  issueParents,
  issuePhaseNext,
  issuePhaseSet,
  issueRelated,
  issueSearch,
  issueShow,
  legacyImport,
  updateArrayField,
} from "./commands"
import { readAllStdin, storeDelete, storeGet, storeKeys, storeSet } from "./commands-store"

export const commands: StringMap<Command> = {
  create: {
    description: "Create a new issue",
    usage: "task create --title <title> [--description <desc>] [--github-issue <number>] [--priority <0-4>] [--label <label>] [--parent <id>]",
    flags: {
      "--title": { description: "Issue title", required: true },
      "--description": { description: "Issue description" },
      "--github-issue": { description: "GitHub issue number" },
      "--priority": { description: "Priority (0=highest, default 2)" },
      "--label": { description: "Label (repeatable)" },
      "--parent": { description: "Parent issue ID for hierarchy" },
    },
    examples: [
      'task create --title "Fix login bug"',
      'task create --title "Urgent fix" --priority 0',
      'task create --title "New feature" --github-issue 42',
      'task create --title "Fix PDF" --label cli --label bug',
      'task create --title "Add child command" --parent ab12',
    ],
    run: (args) => issueCreate(args, detectRepoRoot(process.cwd())),
  },
  show: {
    description: "Show issue details",
    usage: "task show <id> [--fields <csv>] [--compact] [--summary] [--include-stores]",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--fields": { description: "Comma-separated metadata fields to return" },
      "--compact": { description: "Return a compact metadata projection suitable for agents" },
      "--summary": { description: "Return metadata only (omit stores unless --include-stores is passed)" },
      "--include-stores": { description: "Include store names and keys in the output" },
    },
    examples: [
      "task show ab12",
      "task show ab12 --summary",
      "task show ab12 --compact",
      "task show ab12 --fields title,phase,refs",
      "task show --id ab12",
    ],
    positionalId: true,
    run: (args) => issueShow(args, detectRepoRoot(process.cwd())),
  },
  list: {
    description: "List issues",
    usage: "task list [--where key=value] [--label <label>] [--text <query>] [--fields <csv>] [--compact|--full] [--sort priority|updated] [--limit <n>] [--jsonl] [--all]",
    flags: {
      "--where": { description: "Filter by key=value (repeatable, AND logic)" },
      "--label": { description: "Filter by label (repeatable, AND logic)" },
      "--text": { description: "Case-insensitive text search across id, title, description, refs, and labels" },
      "--fields": { description: "Comma-separated fields to return for each issue" },
      "--compact": { description: "Return a compact issue projection suitable for agents (default)" },
      "--full": { description: "Return full issue objects instead of the default compact projection" },
      "--sort": { description: "Sort by priority (default) or updated" },
      "--limit": { description: "Maximum number of results to return" },
      "--jsonl": { description: "Format array output as one JSON object per line" },
      "--all": { description: "Include closed issues" },
    },
    examples: [
      "task list",
      "task list --where status=open",
      "task list --label cli",
      "task list --label cli --label bug",
      'task list --text "packet session"',
      "task list --sort updated",
      "task list --jsonl --all --limit 10",
      "task list --full --limit 1",
    ],
    run: (args) => issueList(args, detectRepoRoot(process.cwd())),
  },
  search: {
    description: "Search issues by text",
    usage: "task search <query> [--fields <csv>] [--compact|--full] [--sort priority|updated] [--limit <n>] [--jsonl] [--all]",
    flags: {
      "--text": { description: "Optional explicit search query (otherwise uses positional query text)" },
      "--fields": { description: "Comma-separated fields to return for each issue" },
      "--compact": { description: "Return a compact issue projection suitable for agents (default)" },
      "--full": { description: "Return full issue objects instead of the default compact projection" },
      "--sort": { description: "Sort by priority (default) or updated" },
      "--limit": { description: "Maximum number of results to return" },
      "--jsonl": { description: "Format array output as one JSON object per line" },
      "--all": { description: "Include closed issues" },
    },
    examples: [
      "task search packet session",
      'task search "new packet session page" --sort updated',
      'task search --text "packet session" --jsonl',
    ],
    run: (args) => issueSearch(args, detectRepoRoot(process.cwd())),
  },
  children: {
    description: "List child issues in the hierarchy under a parent issue",
    usage: "task children <id> [--fields <csv>] [--compact|--full] [--sort priority|updated] [--limit <n>] [--jsonl] [--all]",
    flags: {
      "--id": { description: "Parent issue ID (or pass as the first positional argument)" },
      "--fields": { description: "Comma-separated fields to return for each child issue" },
      "--compact": { description: "Return a compact issue projection suitable for agents (default)" },
      "--full": { description: "Return full issue objects instead of the default compact projection" },
      "--sort": { description: "Sort by priority (default) or updated" },
      "--limit": { description: "Maximum number of results to return" },
      "--jsonl": { description: "Format array output as one JSON object per line" },
      "--all": { description: "Include closed issues" },
    },
    examples: [
      "task children gh549",
      "task children gh549 --sort updated",
      "task children gh549 --fields id,title,phase,status",
      "task children gh549 --full",
      "task children --id gh549",
    ],
    positionalId: true,
    run: (args) => issueChildren(args, detectRepoRoot(process.cwd())),
  },
  parents: {
    description: "List parent issues for an issue in the hierarchy",
    usage: "task parents <id> [--fields <csv>] [--compact|--full] [--sort priority|updated] [--limit <n>] [--jsonl]",
    flags: {
      "--id": { description: "Child issue ID (or pass as the first positional argument)" },
      "--fields": { description: "Comma-separated fields to return for each parent issue" },
      "--compact": { description: "Return a compact issue projection suitable for agents (default)" },
      "--full": { description: "Return full issue objects instead of the default compact projection" },
      "--sort": { description: "Sort by priority (default) or updated" },
      "--limit": { description: "Maximum number of results to return" },
      "--jsonl": { description: "Format array output as one JSON object per line" },
    },
    examples: [
      "task parents ojyb",
      "task parents ojyb --sort updated",
      "task parents ojyb --fields id,title,phase,status",
      "task parents ojyb --full",
      "task parents --id ojyb",
    ],
    positionalId: true,
    run: (args) => issueParents(args, detectRepoRoot(process.cwd())),
  },
  related: {
    description: "List parent and child issues related to an issue",
    usage: "task related <id> [--fields <csv>] [--compact|--full] [--sort priority|updated] [--limit <n>] [--jsonl] [--all]",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--fields": { description: "Comma-separated fields to return for each related issue" },
      "--compact": { description: "Return a compact relation projection suitable for agents (default)" },
      "--full": { description: "Return full issue objects instead of the default compact projection" },
      "--sort": { description: "Sort by priority (default) or updated" },
      "--limit": { description: "Maximum number of results to return" },
      "--jsonl": { description: "Format array output as one JSON object per line" },
      "--all": { description: "Include closed child issues in the results" },
    },
    examples: [
      "task related gh549",
      "task related gh549 --sort updated",
      "task related gh549 --fields id,title,relation,status",
      "task related gh549 --full",
      "task related --id gh549",
    ],
    positionalId: true,
    run: (args) => issueRelated(args, detectRepoRoot(process.cwd())),
  },
  close: {
    description: "Close an issue (append IssueClosed and keep it in place)",
    usage: "task close <id>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
    },
    examples: ["task close ab12", "task close --id ab12"],
    positionalId: true,
    run: (args) => issueClose(args, detectRepoRoot(process.cwd())),
  },
  "phase next": {
    description: "Get the next configured phase for an issue",
    usage: "task phase next <id>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
    },
    examples: ["task phase next ab12", "task phase next --id ab12"],
    positionalId: true,
    run: (args) => issuePhaseNext(args, detectRepoRoot(process.cwd())),
  },
  "phase set": {
    description: "Advance an issue to a configured phase",
    usage: "task phase set <id> --value <phase>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--value": { description: "Next phase", required: true },
    },
    examples: [
      "task phase set 0ov2 --value ready-to-code",
      "task phase set --id 0ov2 --value ready-to-code",
    ],
    positionalId: true,
    run: (args) => issuePhaseSet(args, detectRepoRoot(process.cwd())),
  },
  "legacy import": {
    description: "Import a legacy tracker snapshot into the repo-local .task event store",
    usage: "task legacy import --source <path>",
    flags: {
      "--source": { description: "Path to the legacy tracker root", required: true },
    },
    examples: ["task legacy import --source /tmp/old-issues"],
    run: (args) => legacyImport(args, detectRepoRoot(process.cwd())),
  },
  "meta set": {
    description: "Set a non-reserved metadata field on an issue",
    usage: "task meta set <id> --key <key> --value <value>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--key": { description: "Metadata key", required: true },
      "--value": { description: "Metadata value", required: true },
    },
    examples: [
      "task meta set 0ov2 --key owner --value backend",
      "task meta set --id 0ov2 --key owner --value backend",
    ],
    positionalId: true,
    run: (args) => issueMetaSet(args, detectRepoRoot(process.cwd())),
  },
  "meta get": {
    description: "Get a metadata field from an issue",
    usage: "task meta get <id> --key <key>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--key": { description: "Metadata key", required: true },
    },
    examples: ["task meta get 0ov2 --key phase", "task meta get --id 0ov2 --key phase"],
    positionalId: true,
    run: (args) => issueMetaGet(args, detectRepoRoot(process.cwd())),
  },
  "update label": {
    description: "Add or remove labels on an issue",
    usage: "task update label <id> [--add <label>] [--remove <label>]",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--add": { description: "Label to add (repeatable)" },
      "--remove": { description: "Label to remove (repeatable)" },
    },
    examples: [
      "task update label ab12 --add cli",
      "task update label ab12 --add cli --add bug",
      "task update label ab12 --remove cli",
      "task update label ab12 --remove old --add new",
      "task update label --id ab12 --add cli",
    ],
    positionalId: true,
    run: (args) => updateArrayField(args, "labels", detectRepoRoot(process.cwd())),
  },
  "update refs": {
    description: "Add or remove refs on an issue",
    usage: "task update refs <id> [--add <ref>] [--remove <ref>]",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--add": { description: "Ref to add (repeatable)" },
      "--remove": { description: "Ref to remove (repeatable)" },
    },
    examples: [
      "task update refs ab12 --add m85s",
      "task update refs ab12 --remove m85s",
      "task update refs --id ab12 --add m85s",
    ],
    positionalId: true,
    run: (args) => updateArrayField(args, "refs", detectRepoRoot(process.cwd())),
  },
  "store set": {
    description: "Store a value (from --value, --file, or stdin)",
    usage: "task store set <id> --store <store> --key <key> [--value <val> | --file <path>]",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--store": { description: "Store name", required: true },
      "--key": { description: "Key name", required: true },
      "--value": { description: "Value to store (for simple strings)" },
      "--file": { description: "Read value from file path (for multiline content)" },
    },
    examples: [
      'task store set ab12 --store research --key summary --value "quick note"',
      "task store set ab12 --store research --key details --file /tmp/details.md",
      "echo 'content' | task store set ab12 --store research --key summary",
      'task store set --id ab12 --store research --key summary --value "quick note"',
    ],
    positionalId: true,
    run: (args) => storeSet(args, readAllStdin, detectRepoRoot(process.cwd())),
  },
  "store get": {
    description: "Get a stored value",
    usage: "task store get <id> --store <store> --key <key>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--store": { description: "Store name", required: true },
      "--key": { description: "Key name", required: true },
    },
    examples: [
      "task store get ab12 --store research --key summary",
      "task store get --id ab12 --store research --key summary",
    ],
    positionalId: true,
    run: (args) => storeGet(args, detectRepoRoot(process.cwd())),
  },
  "store keys": {
    description: "List keys in a store",
    usage: "task store keys <id> --store <store>",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--store": { description: "Store name", required: true },
    },
    examples: ["task store keys ab12 --store research", "task store keys --id ab12 --store research"],
    positionalId: true,
    run: (args) => storeKeys(args, detectRepoRoot(process.cwd())),
  },
  "store delete": {
    description: "Delete a key from a store, or delete the entire store if --key is omitted",
    usage: "task store delete <id> --store <store> [--key <key>]",
    flags: {
      "--id": { description: "Issue ID (or pass as the first positional argument)" },
      "--store": { description: "Store name", required: true },
      "--key": { description: "Key name (omit to delete the whole store)" },
    },
    examples: [
      "task store delete ab12 --store research --key summary",
      "task store delete ab12 --store research",
      "task store delete --id ab12 --store research --key summary",
    ],
    positionalId: true,
    run: (args) => storeDelete(args, detectRepoRoot(process.cwd())),
  },
}
